version: '3.1'

services:
  mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: admin
    volumes:
      - ./db/ :/docker-entrypoint-initdb.d/
    
  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8010:80
      environment:
        - PMA_ARBITRARY=1

  php-7.4:
    image: arthurelinux/php74apache
    ports:
      - 8000:80
    volumes:
      - ./joomla:/joomla
      
    depends_on:
      - mysql
      - phpmyadmin